// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOJZCgxZV5O3O5p6B5sUcEUlXVIKo49Ww',
    appId: '1:120596552235:web:7504a0faba739ea401e86e',
    messagingSenderId: '120596552235',
    projectId: 'datas-5b871',
    authDomain: 'datas-5b871.firebaseapp.com',
    storageBucket: 'datas-5b871.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXC6SkLwbhAg3gCO44N1bQNIixRPhhOLw',
    appId: '1:120596552235:android:3b330c5076d93f4a01e86e',
    messagingSenderId: '120596552235',
    projectId: 'datas-5b871',
    storageBucket: 'datas-5b871.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA69mJsAQresoBU-C2D9mfXSJMAsL5yoMM',
    appId: '1:120596552235:ios:af6be7d15dbc83d501e86e',
    messagingSenderId: '120596552235',
    projectId: 'datas-5b871',
    storageBucket: 'datas-5b871.firebasestorage.app',
    iosBundleId: 'com.example.datas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA69mJsAQresoBU-C2D9mfXSJMAsL5yoMM',
    appId: '1:120596552235:ios:af6be7d15dbc83d501e86e',
    messagingSenderId: '120596552235',
    projectId: 'datas-5b871',
    storageBucket: 'datas-5b871.firebasestorage.app',
    iosBundleId: 'com.example.datas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOJZCgxZV5O3O5p6B5sUcEUlXVIKo49Ww',
    appId: '1:120596552235:web:b24d4ea821c5cbb901e86e',
    messagingSenderId: '120596552235',
    projectId: 'datas-5b871',
    authDomain: 'datas-5b871.firebaseapp.com',
    storageBucket: 'datas-5b871.firebasestorage.app',
  );
}
